realcar_path: /workspace/3DRealCar
model_base: /workspace/models/nusc/
# uniad_path: /workspace/UniAD_SIM/tools/e2e.sh
# vad_path:  /nas/users/hyzhou/PAMI2024/release/VAD_Sim/tools/e2e.sh
# ltf_path: /workspace/NAVSIM/ltf_e2e.sh
output_dir: /workspace/outputs
# HD_map:
  # path: /nas/datasets/nuScenes/raw/Trainval
  # version: nusc_trainval