realcar_path: /home/sczone/hugsim_workspace/3DRealCar
model_base: /home/sczone/hugsim_workspace/hugsim_data/zone/
uniad_path: /nas/users/hyzhou/code/UniAD_Sim/tools/e2e.sh
vad_path: /nas/users/hyzhou/code/VAD_Sim/tools/e2e.sh
ltf_path: /nas/users/hyzhou/code/navsim/ltf_e2e.sh
output_dir: /home/sczone/hugsim_workspace/outputs