mode: medium_02
plan_list:
- - 0 #x
  - 30 #z
  - -0.30 #height
  - 0 # start aw is based on ego car's orientation. 0 means same direction as ego.  Right is positive and left is negative.
  - 0 #start velo
  - "2024_07_05_10_58_02"
  - ConstantPlanner
  - {}
- - 3 #x
  - 5 #z
  - -0.30 #height
  - 0 # start aw is based on ego car's orientation. 0 means same direction as ego.  Right is positive and left is negative.
  - 10 #start velo
  - "2024_07_05_11_02_48"
  - ConstantPlanner
  - {}
load_HD_map: false
start_euler:
- 0.0
- 0.0
- 0.0
start_ab:
- 0.0
- 0.0
start_velo: 2
start_steer: 0
scene_name: scene-20250317_161633_1
iteration: 30000